/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CentralRouteImport } from './routes/central'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EstrategicoRouteImport } from './routes/estrategico'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as NegocioRouteImport } from './routes/negocio'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as BlogNovoRouteImport } from './routes/blog.novo'
import { Route as ChamadosIndexRouteImport } from './routes/chamados.index'
import { Route as ChamadosIdRouteImport } from './routes/chamados.$id'
import { Route as PesquisasIndexRouteImport } from './routes/pesquisas.index'
import { Route as PesquisasSlugRouteImport } from './routes/pesquisas.$slug'
import { Route as UsuariosIdRouteImport } from './routes/usuarios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategicoRoute = EstrategicoRouteImport.update({
  id: '/estrategico',
  path: '/estrategico',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNovoRoute = BlogNovoRouteImport.update({
  id: '/blog/novo',
  path: '/blog/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIndexRoute = ChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIdRoute = ChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasIndexRoute = PesquisasIndexRouteImport.update({
  id: '/pesquisas/',
  path: '/pesquisas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasSlugRoute = PesquisasSlugRouteImport.update({
  id: '/pesquisas/$slug',
  path: '/pesquisas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIdRoute = UsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRoute
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/flags': typeof FlagsRoute
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/negocio': typeof NegocioRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/pesquisas/': typeof PesquisasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRoute
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/flags': typeof FlagsRoute
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/negocio': typeof NegocioRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog': typeof BlogIndexRoute
  '/chamados': typeof ChamadosIndexRoute
  '/pesquisas': typeof PesquisasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRoute
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/flags': typeof FlagsRoute
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/negocio': typeof NegocioRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/pesquisas/': typeof PesquisasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/crm'
    | '/design-system'
    | '/estrategico'
    | '/flags'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/negocio'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog/'
    | '/chamados/'
    | '/pesquisas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/crm'
    | '/design-system'
    | '/estrategico'
    | '/flags'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/negocio'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog'
    | '/chamados'
    | '/pesquisas'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/crm'
    | '/design-system'
    | '/estrategico'
    | '/flags'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/negocio'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog/'
    | '/chamados/'
    | '/pesquisas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CentralRoute: typeof CentralRoute
  ConteudoRoute: typeof ConteudoRoute
  CrmRoute: typeof CrmRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EstrategicoRoute: typeof EstrategicoRoute
  FlagsRoute: typeof FlagsRoute
  FunilRoute: typeof FunilRoute
  GovernancaRoute: typeof GovernancaRoute
  KanbanRoute: typeof KanbanRoute
  LogsRoute: typeof LogsRoute
  NegocioRoute: typeof NegocioRoute
  PainelRoute: typeof PainelRoute
  QualidadeRoute: typeof QualidadeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogNovoRoute: typeof BlogNovoRoute
  ChamadosIdRoute: typeof ChamadosIdRoute
  PesquisasSlugRoute: typeof PesquisasSlugRoute
  UsuariosIdRoute: typeof UsuariosIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChamadosIndexRoute: typeof ChamadosIndexRoute
  PesquisasIndexRoute: typeof PesquisasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategico': {
      id: '/estrategico'
      path: '/estrategico'
      fullPath: '/estrategico'
      preLoaderRoute: typeof EstrategicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/novo': {
      id: '/blog/novo'
      path: '/blog/novo'
      fullPath: '/blog/novo'
      preLoaderRoute: typeof BlogNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/': {
      id: '/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof ChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/$id': {
      id: '/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof ChamadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas/': {
      id: '/pesquisas/'
      path: '/pesquisas'
      fullPath: '/pesquisas/'
      preLoaderRoute: typeof PesquisasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas/$slug': {
      id: '/pesquisas/$slug'
      path: '/pesquisas/$slug'
      fullPath: '/pesquisas/$slug'
      preLoaderRoute: typeof PesquisasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/$id': {
      id: '/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof UsuariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditoriaRoute: AuditoriaRoute,
  CentralRoute: CentralRoute,
  ConteudoRoute: ConteudoRoute,
  CrmRoute: CrmRoute,
  DesignSystemRoute: DesignSystemRoute,
  EstrategicoRoute: EstrategicoRoute,
  FlagsRoute: FlagsRoute,
  FunilRoute: FunilRoute,
  GovernancaRoute: GovernancaRoute,
  KanbanRoute: KanbanRoute,
  LogsRoute: LogsRoute,
  NegocioRoute: NegocioRoute,
  PainelRoute: PainelRoute,
  QualidadeRoute: QualidadeRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogIdRoute: BlogIdRoute,
  BlogNovoRoute: BlogNovoRoute,
  ChamadosIdRoute: ChamadosIdRoute,
  PesquisasSlugRoute: PesquisasSlugRoute,
  UsuariosIdRoute: UsuariosIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChamadosIndexRoute: ChamadosIndexRoute,
  PesquisasIndexRoute: PesquisasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
