/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CentralRouteImport } from './routes/central'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EstrategicoRouteImport } from './routes/estrategico'
import { Route as FabricaSocialRouteImport } from './routes/fabrica-social'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ManualDaMarcaRouteImport } from './routes/manual-da-marca'
import { Route as NegocioRouteImport } from './routes/negocio'
import { Route as NumerosRouteImport } from './routes/numeros'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as BlogNovoRouteImport } from './routes/blog.novo'
import { Route as ChamadosIndexRouteImport } from './routes/chamados.index'
import { Route as ChamadosIdRouteImport } from './routes/chamados.$id'
import { Route as ConteudoPoliaIndexRouteImport } from './routes/conteudo-polia.index'
import { Route as ConteudoPoliaSlugRouteImport } from './routes/conteudo-polia.$slug'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmConvitesRouteImport } from './routes/crm/convites'
import { Route as CrmModelosRouteImport } from './routes/crm/modelos'
import { Route as CrmNegociosRouteImport } from './routes/crm/negocios'
import { Route as CrmTarefasRouteImport } from './routes/crm/tarefas'
import { Route as CrmUsuariasRouteImport } from './routes/crm/usuarias'
import { Route as FabricaSocialIndexRouteImport } from './routes/fabrica-social/index'
import { Route as FabricaSocialBibliotecaRouteImport } from './routes/fabrica-social/biblioteca'
import { Route as FabricaSocialConexoesRouteImport } from './routes/fabrica-social/conexoes'
import { Route as FabricaSocialCriarPostagemRouteImport } from './routes/fabrica-social/criar-postagem'
import { Route as FounderIndexRouteImport } from './routes/founder/index'
import { Route as FounderAlertasRouteImport } from './routes/founder/alertas'
import { Route as FounderNumerosRouteImport } from './routes/founder/numeros'
import { Route as FounderSaudeRouteImport } from './routes/founder/saude'
import { Route as PesquisasIndexRouteImport } from './routes/pesquisas.index'
import { Route as PesquisasSlugRouteImport } from './routes/pesquisas.$slug'
import { Route as UsuariosIdRouteImport } from './routes/usuarios.$id'
import { Route as CrmCampanhasIndexRouteImport } from './routes/crm/campanhas.index'
import { Route as CrmCampanhasIdRouteImport } from './routes/crm/campanhas.$id'
import { Route as CrmContatosIndexRouteImport } from './routes/crm/contatos.index'
import { Route as CrmContatosIdRouteImport } from './routes/crm/contatos.$id'
import { Route as FabricaSocialConexoesMetaRouteImport } from './routes/fabrica-social/conexoes.meta'
import { Route as FabricaSocialConexoesTiktokRouteImport } from './routes/fabrica-social/conexoes.tiktok'
import { Route as FounderAnalyticsIndexRouteImport } from './routes/founder/analytics.index'
import { Route as FounderAnalyticsComportamentoRouteImport } from './routes/founder/analytics.comportamento'
import { Route as FounderAnalyticsFuncionalidadesRouteImport } from './routes/founder/analytics.funcionalidades'
import { Route as FounderAnalyticsJornadasRouteImport } from './routes/founder/analytics.jornadas'
import { Route as FounderAnalyticsRetencaoRouteImport } from './routes/founder/analytics.retencao'
import { Route as FounderAnalyticsSegmentosRouteImport } from './routes/founder/analytics.segmentos'
import { Route as FounderAnalyticsSessoesRouteImport } from './routes/founder/analytics.sessoes'
import { Route as FounderAnalyticsUsuariasRouteImport } from './routes/founder/analytics.usuarias'
import { Route as FounderFeaturesExperimentosRouteImport } from './routes/founder/features.experimentos'
import { Route as FounderFeaturesFlagsRouteImport } from './routes/founder/features.flags'
import { Route as FounderFeaturesReleasesRouteImport } from './routes/founder/features.releases'
import { Route as FounderInfraApiRouteImport } from './routes/founder/infra.api'
import { Route as FounderInfraBancoRouteImport } from './routes/founder/infra.banco'
import { Route as FounderInfraIaRouteImport } from './routes/founder/infra.ia'
import { Route as FounderInfraStorageRouteImport } from './routes/founder/infra.storage'
import { Route as FounderNegocioAssinaturasRouteImport } from './routes/founder/negocio.assinaturas'
import { Route as FounderNegocioChurnRouteImport } from './routes/founder/negocio.churn'
import { Route as FounderNegocioConversaoRouteImport } from './routes/founder/negocio.conversao'
import { Route as FounderNegocioReceitaRouteImport } from './routes/founder/negocio.receita'
import { Route as FounderOperacaoErrosRouteImport } from './routes/founder/operacao.erros'
import { Route as FounderOperacaoIntegracoesRouteImport } from './routes/founder/operacao.integracoes'
import { Route as FounderOperacaoJobsRouteImport } from './routes/founder/operacao.jobs'
import { Route as FounderOperacaoLogsRouteImport } from './routes/founder/operacao.logs'
import { Route as FounderProdutoAtivacaoRouteImport } from './routes/founder/produto.ativacao'
import { Route as FounderProdutoExperimentosRouteImport } from './routes/founder/produto.experimentos'
import { Route as FounderProdutoFeedbackRouteImport } from './routes/founder/produto.feedback'
import { Route as FounderProdutoFunilRouteImport } from './routes/founder/produto.funil'
import { Route as FounderAnalyticsUsuariasIdRouteImport } from './routes/founder/analytics.usuarias.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategicoRoute = EstrategicoRouteImport.update({
  id: '/estrategico',
  path: '/estrategico',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaSocialRoute = FabricaSocialRouteImport.update({
  id: '/fabrica-social',
  path: '/fabrica-social',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualDaMarcaRoute = ManualDaMarcaRouteImport.update({
  id: '/manual-da-marca',
  path: '/manual-da-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosRoute = NumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNovoRoute = BlogNovoRouteImport.update({
  id: '/blog/novo',
  path: '/blog/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIndexRoute = ChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIdRoute = ChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoPoliaIndexRoute = ConteudoPoliaIndexRouteImport.update({
  id: '/conteudo-polia/',
  path: '/conteudo-polia/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoPoliaSlugRoute = ConteudoPoliaSlugRouteImport.update({
  id: '/conteudo-polia/$slug',
  path: '/conteudo-polia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmConvitesRoute = CrmConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => CrmRoute,
} as any)
const CrmModelosRoute = CrmModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmNegociosRoute = CrmNegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTarefasRoute = CrmTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmUsuariasRoute = CrmUsuariasRouteImport.update({
  id: '/usuarias',
  path: '/usuarias',
  getParentRoute: () => CrmRoute,
} as any)
const FabricaSocialIndexRoute = FabricaSocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FabricaSocialRoute,
} as any)
const FabricaSocialBibliotecaRoute = FabricaSocialBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => FabricaSocialRoute,
} as any)
const FabricaSocialConexoesRoute = FabricaSocialConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => FabricaSocialRoute,
} as any)
const FabricaSocialCriarPostagemRoute =
  FabricaSocialCriarPostagemRouteImport.update({
    id: '/criar-postagem',
    path: '/criar-postagem',
    getParentRoute: () => FabricaSocialRoute,
  } as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAlertasRoute = FounderAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => FounderRoute,
} as any)
const FounderNumerosRoute = FounderNumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => FounderRoute,
} as any)
const FounderSaudeRoute = FounderSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => FounderRoute,
} as any)
const PesquisasIndexRoute = PesquisasIndexRouteImport.update({
  id: '/pesquisas/',
  path: '/pesquisas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasSlugRoute = PesquisasSlugRouteImport.update({
  id: '/pesquisas/$slug',
  path: '/pesquisas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIdRoute = UsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCampanhasIndexRoute = CrmCampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCampanhasIdRoute = CrmCampanhasIdRouteImport.update({
  id: '/campanhas/$id',
  path: '/campanhas/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContatosIndexRoute = CrmContatosIndexRouteImport.update({
  id: '/contatos/',
  path: '/contatos/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContatosIdRoute = CrmContatosIdRouteImport.update({
  id: '/contatos/$id',
  path: '/contatos/$id',
  getParentRoute: () => CrmRoute,
} as any)
const FabricaSocialConexoesMetaRoute =
  FabricaSocialConexoesMetaRouteImport.update({
    id: '/meta',
    path: '/meta',
    getParentRoute: () => FabricaSocialConexoesRoute,
  } as any)
const FabricaSocialConexoesTiktokRoute =
  FabricaSocialConexoesTiktokRouteImport.update({
    id: '/tiktok',
    path: '/tiktok',
    getParentRoute: () => FabricaSocialConexoesRoute,
  } as any)
const FounderAnalyticsIndexRoute = FounderAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAnalyticsComportamentoRoute =
  FounderAnalyticsComportamentoRouteImport.update({
    id: '/analytics/comportamento',
    path: '/analytics/comportamento',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderAnalyticsFuncionalidadesRoute =
  FounderAnalyticsFuncionalidadesRouteImport.update({
    id: '/analytics/funcionalidades',
    path: '/analytics/funcionalidades',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderAnalyticsJornadasRoute =
  FounderAnalyticsJornadasRouteImport.update({
    id: '/analytics/jornadas',
    path: '/analytics/jornadas',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderAnalyticsRetencaoRoute =
  FounderAnalyticsRetencaoRouteImport.update({
    id: '/analytics/retencao',
    path: '/analytics/retencao',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderAnalyticsSegmentosRoute =
  FounderAnalyticsSegmentosRouteImport.update({
    id: '/analytics/segmentos',
    path: '/analytics/segmentos',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderAnalyticsSessoesRoute = FounderAnalyticsSessoesRouteImport.update({
  id: '/analytics/sessoes',
  path: '/analytics/sessoes',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAnalyticsUsuariasRoute =
  FounderAnalyticsUsuariasRouteImport.update({
    id: '/analytics/usuarias',
    path: '/analytics/usuarias',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderFeaturesExperimentosRoute =
  FounderFeaturesExperimentosRouteImport.update({
    id: '/features/experimentos',
    path: '/features/experimentos',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderFeaturesFlagsRoute = FounderFeaturesFlagsRouteImport.update({
  id: '/features/flags',
  path: '/features/flags',
  getParentRoute: () => FounderRoute,
} as any)
const FounderFeaturesReleasesRoute = FounderFeaturesReleasesRouteImport.update({
  id: '/features/releases',
  path: '/features/releases',
  getParentRoute: () => FounderRoute,
} as any)
const FounderInfraApiRoute = FounderInfraApiRouteImport.update({
  id: '/infra/api',
  path: '/infra/api',
  getParentRoute: () => FounderRoute,
} as any)
const FounderInfraBancoRoute = FounderInfraBancoRouteImport.update({
  id: '/infra/banco',
  path: '/infra/banco',
  getParentRoute: () => FounderRoute,
} as any)
const FounderInfraIaRoute = FounderInfraIaRouteImport.update({
  id: '/infra/ia',
  path: '/infra/ia',
  getParentRoute: () => FounderRoute,
} as any)
const FounderInfraStorageRoute = FounderInfraStorageRouteImport.update({
  id: '/infra/storage',
  path: '/infra/storage',
  getParentRoute: () => FounderRoute,
} as any)
const FounderNegocioAssinaturasRoute =
  FounderNegocioAssinaturasRouteImport.update({
    id: '/negocio/assinaturas',
    path: '/negocio/assinaturas',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderNegocioChurnRoute = FounderNegocioChurnRouteImport.update({
  id: '/negocio/churn',
  path: '/negocio/churn',
  getParentRoute: () => FounderRoute,
} as any)
const FounderNegocioConversaoRoute = FounderNegocioConversaoRouteImport.update({
  id: '/negocio/conversao',
  path: '/negocio/conversao',
  getParentRoute: () => FounderRoute,
} as any)
const FounderNegocioReceitaRoute = FounderNegocioReceitaRouteImport.update({
  id: '/negocio/receita',
  path: '/negocio/receita',
  getParentRoute: () => FounderRoute,
} as any)
const FounderOperacaoErrosRoute = FounderOperacaoErrosRouteImport.update({
  id: '/operacao/erros',
  path: '/operacao/erros',
  getParentRoute: () => FounderRoute,
} as any)
const FounderOperacaoIntegracoesRoute =
  FounderOperacaoIntegracoesRouteImport.update({
    id: '/operacao/integracoes',
    path: '/operacao/integracoes',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderOperacaoJobsRoute = FounderOperacaoJobsRouteImport.update({
  id: '/operacao/jobs',
  path: '/operacao/jobs',
  getParentRoute: () => FounderRoute,
} as any)
const FounderOperacaoLogsRoute = FounderOperacaoLogsRouteImport.update({
  id: '/operacao/logs',
  path: '/operacao/logs',
  getParentRoute: () => FounderRoute,
} as any)
const FounderProdutoAtivacaoRoute = FounderProdutoAtivacaoRouteImport.update({
  id: '/produto/ativacao',
  path: '/produto/ativacao',
  getParentRoute: () => FounderRoute,
} as any)
const FounderProdutoExperimentosRoute =
  FounderProdutoExperimentosRouteImport.update({
    id: '/produto/experimentos',
    path: '/produto/experimentos',
    getParentRoute: () => FounderRoute,
  } as any)
const FounderProdutoFeedbackRoute = FounderProdutoFeedbackRouteImport.update({
  id: '/produto/feedback',
  path: '/produto/feedback',
  getParentRoute: () => FounderRoute,
} as any)
const FounderProdutoFunilRoute = FounderProdutoFunilRouteImport.update({
  id: '/produto/funil',
  path: '/produto/funil',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAnalyticsUsuariasIdRoute =
  FounderAnalyticsUsuariasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => FounderAnalyticsUsuariasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/fabrica-social': typeof FabricaSocialRouteWithChildren
  '/ferramentas': typeof FerramentasRoute
  '/flags': typeof FlagsRoute
  '/founder': typeof FounderRouteWithChildren
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/manual-da-marca': typeof ManualDaMarcaRoute
  '/negocio': typeof NegocioRoute
  '/numeros': typeof NumerosRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/conteudo-polia/$slug': typeof ConteudoPoliaSlugRoute
  '/crm/convites': typeof CrmConvitesRoute
  '/crm/modelos': typeof CrmModelosRoute
  '/crm/negocios': typeof CrmNegociosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/usuarias': typeof CrmUsuariasRoute
  '/fabrica-social/biblioteca': typeof FabricaSocialBibliotecaRoute
  '/fabrica-social/conexoes': typeof FabricaSocialConexoesRouteWithChildren
  '/fabrica-social/criar-postagem': typeof FabricaSocialCriarPostagemRoute
  '/founder/alertas': typeof FounderAlertasRoute
  '/founder/numeros': typeof FounderNumerosRoute
  '/founder/saude': typeof FounderSaudeRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/conteudo-polia/': typeof ConteudoPoliaIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/fabrica-social/': typeof FabricaSocialIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/pesquisas/': typeof PesquisasIndexRoute
  '/crm/campanhas/$id': typeof CrmCampanhasIdRoute
  '/crm/contatos/$id': typeof CrmContatosIdRoute
  '/fabrica-social/conexoes/meta': typeof FabricaSocialConexoesMetaRoute
  '/fabrica-social/conexoes/tiktok': typeof FabricaSocialConexoesTiktokRoute
  '/founder/analytics/comportamento': typeof FounderAnalyticsComportamentoRoute
  '/founder/analytics/funcionalidades': typeof FounderAnalyticsFuncionalidadesRoute
  '/founder/analytics/jornadas': typeof FounderAnalyticsJornadasRoute
  '/founder/analytics/retencao': typeof FounderAnalyticsRetencaoRoute
  '/founder/analytics/segmentos': typeof FounderAnalyticsSegmentosRoute
  '/founder/analytics/sessoes': typeof FounderAnalyticsSessoesRoute
  '/founder/analytics/usuarias': typeof FounderAnalyticsUsuariasRouteWithChildren
  '/founder/features/experimentos': typeof FounderFeaturesExperimentosRoute
  '/founder/features/flags': typeof FounderFeaturesFlagsRoute
  '/founder/features/releases': typeof FounderFeaturesReleasesRoute
  '/founder/infra/api': typeof FounderInfraApiRoute
  '/founder/infra/banco': typeof FounderInfraBancoRoute
  '/founder/infra/ia': typeof FounderInfraIaRoute
  '/founder/infra/storage': typeof FounderInfraStorageRoute
  '/founder/negocio/assinaturas': typeof FounderNegocioAssinaturasRoute
  '/founder/negocio/churn': typeof FounderNegocioChurnRoute
  '/founder/negocio/conversao': typeof FounderNegocioConversaoRoute
  '/founder/negocio/receita': typeof FounderNegocioReceitaRoute
  '/founder/operacao/erros': typeof FounderOperacaoErrosRoute
  '/founder/operacao/integracoes': typeof FounderOperacaoIntegracoesRoute
  '/founder/operacao/jobs': typeof FounderOperacaoJobsRoute
  '/founder/operacao/logs': typeof FounderOperacaoLogsRoute
  '/founder/produto/ativacao': typeof FounderProdutoAtivacaoRoute
  '/founder/produto/experimentos': typeof FounderProdutoExperimentosRoute
  '/founder/produto/feedback': typeof FounderProdutoFeedbackRoute
  '/founder/produto/funil': typeof FounderProdutoFunilRoute
  '/crm/campanhas/': typeof CrmCampanhasIndexRoute
  '/crm/contatos/': typeof CrmContatosIndexRoute
  '/founder/analytics/': typeof FounderAnalyticsIndexRoute
  '/founder/analytics/usuarias/$id': typeof FounderAnalyticsUsuariasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/ferramentas': typeof FerramentasRoute
  '/flags': typeof FlagsRoute
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/manual-da-marca': typeof ManualDaMarcaRoute
  '/negocio': typeof NegocioRoute
  '/numeros': typeof NumerosRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/conteudo-polia/$slug': typeof ConteudoPoliaSlugRoute
  '/crm/convites': typeof CrmConvitesRoute
  '/crm/modelos': typeof CrmModelosRoute
  '/crm/negocios': typeof CrmNegociosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/usuarias': typeof CrmUsuariasRoute
  '/fabrica-social/biblioteca': typeof FabricaSocialBibliotecaRoute
  '/fabrica-social/conexoes': typeof FabricaSocialConexoesRouteWithChildren
  '/fabrica-social/criar-postagem': typeof FabricaSocialCriarPostagemRoute
  '/founder/alertas': typeof FounderAlertasRoute
  '/founder/numeros': typeof FounderNumerosRoute
  '/founder/saude': typeof FounderSaudeRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog': typeof BlogIndexRoute
  '/chamados': typeof ChamadosIndexRoute
  '/conteudo-polia': typeof ConteudoPoliaIndexRoute
  '/crm': typeof CrmIndexRoute
  '/fabrica-social': typeof FabricaSocialIndexRoute
  '/founder': typeof FounderIndexRoute
  '/pesquisas': typeof PesquisasIndexRoute
  '/crm/campanhas/$id': typeof CrmCampanhasIdRoute
  '/crm/contatos/$id': typeof CrmContatosIdRoute
  '/fabrica-social/conexoes/meta': typeof FabricaSocialConexoesMetaRoute
  '/fabrica-social/conexoes/tiktok': typeof FabricaSocialConexoesTiktokRoute
  '/founder/analytics/comportamento': typeof FounderAnalyticsComportamentoRoute
  '/founder/analytics/funcionalidades': typeof FounderAnalyticsFuncionalidadesRoute
  '/founder/analytics/jornadas': typeof FounderAnalyticsJornadasRoute
  '/founder/analytics/retencao': typeof FounderAnalyticsRetencaoRoute
  '/founder/analytics/segmentos': typeof FounderAnalyticsSegmentosRoute
  '/founder/analytics/sessoes': typeof FounderAnalyticsSessoesRoute
  '/founder/analytics/usuarias': typeof FounderAnalyticsUsuariasRouteWithChildren
  '/founder/features/experimentos': typeof FounderFeaturesExperimentosRoute
  '/founder/features/flags': typeof FounderFeaturesFlagsRoute
  '/founder/features/releases': typeof FounderFeaturesReleasesRoute
  '/founder/infra/api': typeof FounderInfraApiRoute
  '/founder/infra/banco': typeof FounderInfraBancoRoute
  '/founder/infra/ia': typeof FounderInfraIaRoute
  '/founder/infra/storage': typeof FounderInfraStorageRoute
  '/founder/negocio/assinaturas': typeof FounderNegocioAssinaturasRoute
  '/founder/negocio/churn': typeof FounderNegocioChurnRoute
  '/founder/negocio/conversao': typeof FounderNegocioConversaoRoute
  '/founder/negocio/receita': typeof FounderNegocioReceitaRoute
  '/founder/operacao/erros': typeof FounderOperacaoErrosRoute
  '/founder/operacao/integracoes': typeof FounderOperacaoIntegracoesRoute
  '/founder/operacao/jobs': typeof FounderOperacaoJobsRoute
  '/founder/operacao/logs': typeof FounderOperacaoLogsRoute
  '/founder/produto/ativacao': typeof FounderProdutoAtivacaoRoute
  '/founder/produto/experimentos': typeof FounderProdutoExperimentosRoute
  '/founder/produto/feedback': typeof FounderProdutoFeedbackRoute
  '/founder/produto/funil': typeof FounderProdutoFunilRoute
  '/crm/campanhas': typeof CrmCampanhasIndexRoute
  '/crm/contatos': typeof CrmContatosIndexRoute
  '/founder/analytics': typeof FounderAnalyticsIndexRoute
  '/founder/analytics/usuarias/$id': typeof FounderAnalyticsUsuariasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/estrategico': typeof EstrategicoRoute
  '/fabrica-social': typeof FabricaSocialRouteWithChildren
  '/ferramentas': typeof FerramentasRoute
  '/flags': typeof FlagsRoute
  '/founder': typeof FounderRouteWithChildren
  '/funil': typeof FunilRoute
  '/governanca': typeof GovernancaRoute
  '/kanban': typeof KanbanRoute
  '/logs': typeof LogsRoute
  '/manual-da-marca': typeof ManualDaMarcaRoute
  '/negocio': typeof NegocioRoute
  '/numeros': typeof NumerosRoute
  '/painel': typeof PainelRoute
  '/qualidade': typeof QualidadeRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/novo': typeof BlogNovoRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/conteudo-polia/$slug': typeof ConteudoPoliaSlugRoute
  '/crm/convites': typeof CrmConvitesRoute
  '/crm/modelos': typeof CrmModelosRoute
  '/crm/negocios': typeof CrmNegociosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/usuarias': typeof CrmUsuariasRoute
  '/fabrica-social/biblioteca': typeof FabricaSocialBibliotecaRoute
  '/fabrica-social/conexoes': typeof FabricaSocialConexoesRouteWithChildren
  '/fabrica-social/criar-postagem': typeof FabricaSocialCriarPostagemRoute
  '/founder/alertas': typeof FounderAlertasRoute
  '/founder/numeros': typeof FounderNumerosRoute
  '/founder/saude': typeof FounderSaudeRoute
  '/pesquisas/$slug': typeof PesquisasSlugRoute
  '/usuarios/$id': typeof UsuariosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/conteudo-polia/': typeof ConteudoPoliaIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/fabrica-social/': typeof FabricaSocialIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/pesquisas/': typeof PesquisasIndexRoute
  '/crm/campanhas/$id': typeof CrmCampanhasIdRoute
  '/crm/contatos/$id': typeof CrmContatosIdRoute
  '/fabrica-social/conexoes/meta': typeof FabricaSocialConexoesMetaRoute
  '/fabrica-social/conexoes/tiktok': typeof FabricaSocialConexoesTiktokRoute
  '/founder/analytics/comportamento': typeof FounderAnalyticsComportamentoRoute
  '/founder/analytics/funcionalidades': typeof FounderAnalyticsFuncionalidadesRoute
  '/founder/analytics/jornadas': typeof FounderAnalyticsJornadasRoute
  '/founder/analytics/retencao': typeof FounderAnalyticsRetencaoRoute
  '/founder/analytics/segmentos': typeof FounderAnalyticsSegmentosRoute
  '/founder/analytics/sessoes': typeof FounderAnalyticsSessoesRoute
  '/founder/analytics/usuarias': typeof FounderAnalyticsUsuariasRouteWithChildren
  '/founder/features/experimentos': typeof FounderFeaturesExperimentosRoute
  '/founder/features/flags': typeof FounderFeaturesFlagsRoute
  '/founder/features/releases': typeof FounderFeaturesReleasesRoute
  '/founder/infra/api': typeof FounderInfraApiRoute
  '/founder/infra/banco': typeof FounderInfraBancoRoute
  '/founder/infra/ia': typeof FounderInfraIaRoute
  '/founder/infra/storage': typeof FounderInfraStorageRoute
  '/founder/negocio/assinaturas': typeof FounderNegocioAssinaturasRoute
  '/founder/negocio/churn': typeof FounderNegocioChurnRoute
  '/founder/negocio/conversao': typeof FounderNegocioConversaoRoute
  '/founder/negocio/receita': typeof FounderNegocioReceitaRoute
  '/founder/operacao/erros': typeof FounderOperacaoErrosRoute
  '/founder/operacao/integracoes': typeof FounderOperacaoIntegracoesRoute
  '/founder/operacao/jobs': typeof FounderOperacaoJobsRoute
  '/founder/operacao/logs': typeof FounderOperacaoLogsRoute
  '/founder/produto/ativacao': typeof FounderProdutoAtivacaoRoute
  '/founder/produto/experimentos': typeof FounderProdutoExperimentosRoute
  '/founder/produto/feedback': typeof FounderProdutoFeedbackRoute
  '/founder/produto/funil': typeof FounderProdutoFunilRoute
  '/crm/campanhas/': typeof CrmCampanhasIndexRoute
  '/crm/contatos/': typeof CrmContatosIndexRoute
  '/founder/analytics/': typeof FounderAnalyticsIndexRoute
  '/founder/analytics/usuarias/$id': typeof FounderAnalyticsUsuariasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/crm'
    | '/design-system'
    | '/estrategico'
    | '/fabrica-social'
    | '/ferramentas'
    | '/flags'
    | '/founder'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/manual-da-marca'
    | '/negocio'
    | '/numeros'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/conteudo-polia/$slug'
    | '/crm/convites'
    | '/crm/modelos'
    | '/crm/negocios'
    | '/crm/tarefas'
    | '/crm/usuarias'
    | '/fabrica-social/biblioteca'
    | '/fabrica-social/conexoes'
    | '/fabrica-social/criar-postagem'
    | '/founder/alertas'
    | '/founder/numeros'
    | '/founder/saude'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog/'
    | '/chamados/'
    | '/conteudo-polia/'
    | '/crm/'
    | '/fabrica-social/'
    | '/founder/'
    | '/pesquisas/'
    | '/crm/campanhas/$id'
    | '/crm/contatos/$id'
    | '/fabrica-social/conexoes/meta'
    | '/fabrica-social/conexoes/tiktok'
    | '/founder/analytics/comportamento'
    | '/founder/analytics/funcionalidades'
    | '/founder/analytics/jornadas'
    | '/founder/analytics/retencao'
    | '/founder/analytics/segmentos'
    | '/founder/analytics/sessoes'
    | '/founder/analytics/usuarias'
    | '/founder/features/experimentos'
    | '/founder/features/flags'
    | '/founder/features/releases'
    | '/founder/infra/api'
    | '/founder/infra/banco'
    | '/founder/infra/ia'
    | '/founder/infra/storage'
    | '/founder/negocio/assinaturas'
    | '/founder/negocio/churn'
    | '/founder/negocio/conversao'
    | '/founder/negocio/receita'
    | '/founder/operacao/erros'
    | '/founder/operacao/integracoes'
    | '/founder/operacao/jobs'
    | '/founder/operacao/logs'
    | '/founder/produto/ativacao'
    | '/founder/produto/experimentos'
    | '/founder/produto/feedback'
    | '/founder/produto/funil'
    | '/crm/campanhas/'
    | '/crm/contatos/'
    | '/founder/analytics/'
    | '/founder/analytics/usuarias/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/design-system'
    | '/estrategico'
    | '/ferramentas'
    | '/flags'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/manual-da-marca'
    | '/negocio'
    | '/numeros'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/conteudo-polia/$slug'
    | '/crm/convites'
    | '/crm/modelos'
    | '/crm/negocios'
    | '/crm/tarefas'
    | '/crm/usuarias'
    | '/fabrica-social/biblioteca'
    | '/fabrica-social/conexoes'
    | '/fabrica-social/criar-postagem'
    | '/founder/alertas'
    | '/founder/numeros'
    | '/founder/saude'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog'
    | '/chamados'
    | '/conteudo-polia'
    | '/crm'
    | '/fabrica-social'
    | '/founder'
    | '/pesquisas'
    | '/crm/campanhas/$id'
    | '/crm/contatos/$id'
    | '/fabrica-social/conexoes/meta'
    | '/fabrica-social/conexoes/tiktok'
    | '/founder/analytics/comportamento'
    | '/founder/analytics/funcionalidades'
    | '/founder/analytics/jornadas'
    | '/founder/analytics/retencao'
    | '/founder/analytics/segmentos'
    | '/founder/analytics/sessoes'
    | '/founder/analytics/usuarias'
    | '/founder/features/experimentos'
    | '/founder/features/flags'
    | '/founder/features/releases'
    | '/founder/infra/api'
    | '/founder/infra/banco'
    | '/founder/infra/ia'
    | '/founder/infra/storage'
    | '/founder/negocio/assinaturas'
    | '/founder/negocio/churn'
    | '/founder/negocio/conversao'
    | '/founder/negocio/receita'
    | '/founder/operacao/erros'
    | '/founder/operacao/integracoes'
    | '/founder/operacao/jobs'
    | '/founder/operacao/logs'
    | '/founder/produto/ativacao'
    | '/founder/produto/experimentos'
    | '/founder/produto/feedback'
    | '/founder/produto/funil'
    | '/crm/campanhas'
    | '/crm/contatos'
    | '/founder/analytics'
    | '/founder/analytics/usuarias/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analytics'
    | '/auditoria'
    | '/central'
    | '/conteudo'
    | '/crm'
    | '/design-system'
    | '/estrategico'
    | '/fabrica-social'
    | '/ferramentas'
    | '/flags'
    | '/founder'
    | '/funil'
    | '/governanca'
    | '/kanban'
    | '/logs'
    | '/manual-da-marca'
    | '/negocio'
    | '/numeros'
    | '/painel'
    | '/qualidade'
    | '/auth/login'
    | '/blog/$id'
    | '/blog/novo'
    | '/chamados/$id'
    | '/conteudo-polia/$slug'
    | '/crm/convites'
    | '/crm/modelos'
    | '/crm/negocios'
    | '/crm/tarefas'
    | '/crm/usuarias'
    | '/fabrica-social/biblioteca'
    | '/fabrica-social/conexoes'
    | '/fabrica-social/criar-postagem'
    | '/founder/alertas'
    | '/founder/numeros'
    | '/founder/saude'
    | '/pesquisas/$slug'
    | '/usuarios/$id'
    | '/blog/'
    | '/chamados/'
    | '/conteudo-polia/'
    | '/crm/'
    | '/fabrica-social/'
    | '/founder/'
    | '/pesquisas/'
    | '/crm/campanhas/$id'
    | '/crm/contatos/$id'
    | '/fabrica-social/conexoes/meta'
    | '/fabrica-social/conexoes/tiktok'
    | '/founder/analytics/comportamento'
    | '/founder/analytics/funcionalidades'
    | '/founder/analytics/jornadas'
    | '/founder/analytics/retencao'
    | '/founder/analytics/segmentos'
    | '/founder/analytics/sessoes'
    | '/founder/analytics/usuarias'
    | '/founder/features/experimentos'
    | '/founder/features/flags'
    | '/founder/features/releases'
    | '/founder/infra/api'
    | '/founder/infra/banco'
    | '/founder/infra/ia'
    | '/founder/infra/storage'
    | '/founder/negocio/assinaturas'
    | '/founder/negocio/churn'
    | '/founder/negocio/conversao'
    | '/founder/negocio/receita'
    | '/founder/operacao/erros'
    | '/founder/operacao/integracoes'
    | '/founder/operacao/jobs'
    | '/founder/operacao/logs'
    | '/founder/produto/ativacao'
    | '/founder/produto/experimentos'
    | '/founder/produto/feedback'
    | '/founder/produto/funil'
    | '/crm/campanhas/'
    | '/crm/contatos/'
    | '/founder/analytics/'
    | '/founder/analytics/usuarias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CentralRoute: typeof CentralRoute
  ConteudoRoute: typeof ConteudoRoute
  CrmRoute: typeof CrmRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  EstrategicoRoute: typeof EstrategicoRoute
  FabricaSocialRoute: typeof FabricaSocialRouteWithChildren
  FerramentasRoute: typeof FerramentasRoute
  FlagsRoute: typeof FlagsRoute
  FounderRoute: typeof FounderRouteWithChildren
  FunilRoute: typeof FunilRoute
  GovernancaRoute: typeof GovernancaRoute
  KanbanRoute: typeof KanbanRoute
  LogsRoute: typeof LogsRoute
  ManualDaMarcaRoute: typeof ManualDaMarcaRoute
  NegocioRoute: typeof NegocioRoute
  NumerosRoute: typeof NumerosRoute
  PainelRoute: typeof PainelRoute
  QualidadeRoute: typeof QualidadeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogNovoRoute: typeof BlogNovoRoute
  ChamadosIdRoute: typeof ChamadosIdRoute
  ConteudoPoliaSlugRoute: typeof ConteudoPoliaSlugRoute
  PesquisasSlugRoute: typeof PesquisasSlugRoute
  UsuariosIdRoute: typeof UsuariosIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChamadosIndexRoute: typeof ChamadosIndexRoute
  ConteudoPoliaIndexRoute: typeof ConteudoPoliaIndexRoute
  PesquisasIndexRoute: typeof PesquisasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategico': {
      id: '/estrategico'
      path: '/estrategico'
      fullPath: '/estrategico'
      preLoaderRoute: typeof EstrategicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica-social': {
      id: '/fabrica-social'
      path: '/fabrica-social'
      fullPath: '/fabrica-social'
      preLoaderRoute: typeof FabricaSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-da-marca': {
      id: '/manual-da-marca'
      path: '/manual-da-marca'
      fullPath: '/manual-da-marca'
      preLoaderRoute: typeof ManualDaMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros': {
      id: '/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof NumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/novo': {
      id: '/blog/novo'
      path: '/blog/novo'
      fullPath: '/blog/novo'
      preLoaderRoute: typeof BlogNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/': {
      id: '/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof ChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/$id': {
      id: '/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof ChamadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo-polia/': {
      id: '/conteudo-polia/'
      path: '/conteudo-polia'
      fullPath: '/conteudo-polia/'
      preLoaderRoute: typeof ConteudoPoliaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo-polia/$slug': {
      id: '/conteudo-polia/$slug'
      path: '/conteudo-polia/$slug'
      fullPath: '/conteudo-polia/$slug'
      preLoaderRoute: typeof ConteudoPoliaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/convites': {
      id: '/crm/convites'
      path: '/convites'
      fullPath: '/crm/convites'
      preLoaderRoute: typeof CrmConvitesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/modelos': {
      id: '/crm/modelos'
      path: '/modelos'
      fullPath: '/crm/modelos'
      preLoaderRoute: typeof CrmModelosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/negocios': {
      id: '/crm/negocios'
      path: '/negocios'
      fullPath: '/crm/negocios'
      preLoaderRoute: typeof CrmNegociosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tarefas': {
      id: '/crm/tarefas'
      path: '/tarefas'
      fullPath: '/crm/tarefas'
      preLoaderRoute: typeof CrmTarefasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/usuarias': {
      id: '/crm/usuarias'
      path: '/usuarias'
      fullPath: '/crm/usuarias'
      preLoaderRoute: typeof CrmUsuariasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/fabrica-social/': {
      id: '/fabrica-social/'
      path: '/'
      fullPath: '/fabrica-social/'
      preLoaderRoute: typeof FabricaSocialIndexRouteImport
      parentRoute: typeof FabricaSocialRoute
    }
    '/fabrica-social/biblioteca': {
      id: '/fabrica-social/biblioteca'
      path: '/biblioteca'
      fullPath: '/fabrica-social/biblioteca'
      preLoaderRoute: typeof FabricaSocialBibliotecaRouteImport
      parentRoute: typeof FabricaSocialRoute
    }
    '/fabrica-social/conexoes': {
      id: '/fabrica-social/conexoes'
      path: '/conexoes'
      fullPath: '/fabrica-social/conexoes'
      preLoaderRoute: typeof FabricaSocialConexoesRouteImport
      parentRoute: typeof FabricaSocialRoute
    }
    '/fabrica-social/criar-postagem': {
      id: '/fabrica-social/criar-postagem'
      path: '/criar-postagem'
      fullPath: '/fabrica-social/criar-postagem'
      preLoaderRoute: typeof FabricaSocialCriarPostagemRouteImport
      parentRoute: typeof FabricaSocialRoute
    }
    '/founder/': {
      id: '/founder/'
      path: '/'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/alertas': {
      id: '/founder/alertas'
      path: '/alertas'
      fullPath: '/founder/alertas'
      preLoaderRoute: typeof FounderAlertasRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/numeros': {
      id: '/founder/numeros'
      path: '/numeros'
      fullPath: '/founder/numeros'
      preLoaderRoute: typeof FounderNumerosRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/saude': {
      id: '/founder/saude'
      path: '/saude'
      fullPath: '/founder/saude'
      preLoaderRoute: typeof FounderSaudeRouteImport
      parentRoute: typeof FounderRoute
    }
    '/pesquisas/': {
      id: '/pesquisas/'
      path: '/pesquisas'
      fullPath: '/pesquisas/'
      preLoaderRoute: typeof PesquisasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas/$slug': {
      id: '/pesquisas/$slug'
      path: '/pesquisas/$slug'
      fullPath: '/pesquisas/$slug'
      preLoaderRoute: typeof PesquisasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/$id': {
      id: '/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof UsuariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/campanhas/': {
      id: '/crm/campanhas/'
      path: '/campanhas'
      fullPath: '/crm/campanhas/'
      preLoaderRoute: typeof CrmCampanhasIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/campanhas/$id': {
      id: '/crm/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/crm/campanhas/$id'
      preLoaderRoute: typeof CrmCampanhasIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contatos/': {
      id: '/crm/contatos/'
      path: '/contatos'
      fullPath: '/crm/contatos/'
      preLoaderRoute: typeof CrmContatosIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contatos/$id': {
      id: '/crm/contatos/$id'
      path: '/contatos/$id'
      fullPath: '/crm/contatos/$id'
      preLoaderRoute: typeof CrmContatosIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/fabrica-social/conexoes/meta': {
      id: '/fabrica-social/conexoes/meta'
      path: '/meta'
      fullPath: '/fabrica-social/conexoes/meta'
      preLoaderRoute: typeof FabricaSocialConexoesMetaRouteImport
      parentRoute: typeof FabricaSocialConexoesRoute
    }
    '/fabrica-social/conexoes/tiktok': {
      id: '/fabrica-social/conexoes/tiktok'
      path: '/tiktok'
      fullPath: '/fabrica-social/conexoes/tiktok'
      preLoaderRoute: typeof FabricaSocialConexoesTiktokRouteImport
      parentRoute: typeof FabricaSocialConexoesRoute
    }
    '/founder/analytics/': {
      id: '/founder/analytics/'
      path: '/analytics'
      fullPath: '/founder/analytics/'
      preLoaderRoute: typeof FounderAnalyticsIndexRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/comportamento': {
      id: '/founder/analytics/comportamento'
      path: '/analytics/comportamento'
      fullPath: '/founder/analytics/comportamento'
      preLoaderRoute: typeof FounderAnalyticsComportamentoRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/funcionalidades': {
      id: '/founder/analytics/funcionalidades'
      path: '/analytics/funcionalidades'
      fullPath: '/founder/analytics/funcionalidades'
      preLoaderRoute: typeof FounderAnalyticsFuncionalidadesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/jornadas': {
      id: '/founder/analytics/jornadas'
      path: '/analytics/jornadas'
      fullPath: '/founder/analytics/jornadas'
      preLoaderRoute: typeof FounderAnalyticsJornadasRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/retencao': {
      id: '/founder/analytics/retencao'
      path: '/analytics/retencao'
      fullPath: '/founder/analytics/retencao'
      preLoaderRoute: typeof FounderAnalyticsRetencaoRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/segmentos': {
      id: '/founder/analytics/segmentos'
      path: '/analytics/segmentos'
      fullPath: '/founder/analytics/segmentos'
      preLoaderRoute: typeof FounderAnalyticsSegmentosRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/sessoes': {
      id: '/founder/analytics/sessoes'
      path: '/analytics/sessoes'
      fullPath: '/founder/analytics/sessoes'
      preLoaderRoute: typeof FounderAnalyticsSessoesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/usuarias': {
      id: '/founder/analytics/usuarias'
      path: '/analytics/usuarias'
      fullPath: '/founder/analytics/usuarias'
      preLoaderRoute: typeof FounderAnalyticsUsuariasRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/features/experimentos': {
      id: '/founder/features/experimentos'
      path: '/features/experimentos'
      fullPath: '/founder/features/experimentos'
      preLoaderRoute: typeof FounderFeaturesExperimentosRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/features/flags': {
      id: '/founder/features/flags'
      path: '/features/flags'
      fullPath: '/founder/features/flags'
      preLoaderRoute: typeof FounderFeaturesFlagsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/features/releases': {
      id: '/founder/features/releases'
      path: '/features/releases'
      fullPath: '/founder/features/releases'
      preLoaderRoute: typeof FounderFeaturesReleasesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/infra/api': {
      id: '/founder/infra/api'
      path: '/infra/api'
      fullPath: '/founder/infra/api'
      preLoaderRoute: typeof FounderInfraApiRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/infra/banco': {
      id: '/founder/infra/banco'
      path: '/infra/banco'
      fullPath: '/founder/infra/banco'
      preLoaderRoute: typeof FounderInfraBancoRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/infra/ia': {
      id: '/founder/infra/ia'
      path: '/infra/ia'
      fullPath: '/founder/infra/ia'
      preLoaderRoute: typeof FounderInfraIaRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/infra/storage': {
      id: '/founder/infra/storage'
      path: '/infra/storage'
      fullPath: '/founder/infra/storage'
      preLoaderRoute: typeof FounderInfraStorageRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/negocio/assinaturas': {
      id: '/founder/negocio/assinaturas'
      path: '/negocio/assinaturas'
      fullPath: '/founder/negocio/assinaturas'
      preLoaderRoute: typeof FounderNegocioAssinaturasRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/negocio/churn': {
      id: '/founder/negocio/churn'
      path: '/negocio/churn'
      fullPath: '/founder/negocio/churn'
      preLoaderRoute: typeof FounderNegocioChurnRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/negocio/conversao': {
      id: '/founder/negocio/conversao'
      path: '/negocio/conversao'
      fullPath: '/founder/negocio/conversao'
      preLoaderRoute: typeof FounderNegocioConversaoRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/negocio/receita': {
      id: '/founder/negocio/receita'
      path: '/negocio/receita'
      fullPath: '/founder/negocio/receita'
      preLoaderRoute: typeof FounderNegocioReceitaRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/operacao/erros': {
      id: '/founder/operacao/erros'
      path: '/operacao/erros'
      fullPath: '/founder/operacao/erros'
      preLoaderRoute: typeof FounderOperacaoErrosRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/operacao/integracoes': {
      id: '/founder/operacao/integracoes'
      path: '/operacao/integracoes'
      fullPath: '/founder/operacao/integracoes'
      preLoaderRoute: typeof FounderOperacaoIntegracoesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/operacao/jobs': {
      id: '/founder/operacao/jobs'
      path: '/operacao/jobs'
      fullPath: '/founder/operacao/jobs'
      preLoaderRoute: typeof FounderOperacaoJobsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/operacao/logs': {
      id: '/founder/operacao/logs'
      path: '/operacao/logs'
      fullPath: '/founder/operacao/logs'
      preLoaderRoute: typeof FounderOperacaoLogsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/produto/ativacao': {
      id: '/founder/produto/ativacao'
      path: '/produto/ativacao'
      fullPath: '/founder/produto/ativacao'
      preLoaderRoute: typeof FounderProdutoAtivacaoRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/produto/experimentos': {
      id: '/founder/produto/experimentos'
      path: '/produto/experimentos'
      fullPath: '/founder/produto/experimentos'
      preLoaderRoute: typeof FounderProdutoExperimentosRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/produto/feedback': {
      id: '/founder/produto/feedback'
      path: '/produto/feedback'
      fullPath: '/founder/produto/feedback'
      preLoaderRoute: typeof FounderProdutoFeedbackRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/produto/funil': {
      id: '/founder/produto/funil'
      path: '/produto/funil'
      fullPath: '/founder/produto/funil'
      preLoaderRoute: typeof FounderProdutoFunilRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/analytics/usuarias/$id': {
      id: '/founder/analytics/usuarias/$id'
      path: '/$id'
      fullPath: '/founder/analytics/usuarias/$id'
      preLoaderRoute: typeof FounderAnalyticsUsuariasIdRouteImport
      parentRoute: typeof FounderAnalyticsUsuariasRoute
    }
  }
}

interface CrmRouteChildren {
  CrmConvitesRoute: typeof CrmConvitesRoute
  CrmModelosRoute: typeof CrmModelosRoute
  CrmNegociosRoute: typeof CrmNegociosRoute
  CrmTarefasRoute: typeof CrmTarefasRoute
  CrmUsuariasRoute: typeof CrmUsuariasRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmCampanhasIdRoute: typeof CrmCampanhasIdRoute
  CrmContatosIdRoute: typeof CrmContatosIdRoute
  CrmCampanhasIndexRoute: typeof CrmCampanhasIndexRoute
  CrmContatosIndexRoute: typeof CrmContatosIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmConvitesRoute: CrmConvitesRoute,
  CrmModelosRoute: CrmModelosRoute,
  CrmNegociosRoute: CrmNegociosRoute,
  CrmTarefasRoute: CrmTarefasRoute,
  CrmUsuariasRoute: CrmUsuariasRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmCampanhasIdRoute: CrmCampanhasIdRoute,
  CrmContatosIdRoute: CrmContatosIdRoute,
  CrmCampanhasIndexRoute: CrmCampanhasIndexRoute,
  CrmContatosIndexRoute: CrmContatosIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface FabricaSocialConexoesRouteChildren {
  FabricaSocialConexoesMetaRoute: typeof FabricaSocialConexoesMetaRoute
  FabricaSocialConexoesTiktokRoute: typeof FabricaSocialConexoesTiktokRoute
}

const FabricaSocialConexoesRouteChildren: FabricaSocialConexoesRouteChildren = {
  FabricaSocialConexoesMetaRoute: FabricaSocialConexoesMetaRoute,
  FabricaSocialConexoesTiktokRoute: FabricaSocialConexoesTiktokRoute,
}

const FabricaSocialConexoesRouteWithChildren =
  FabricaSocialConexoesRoute._addFileChildren(
    FabricaSocialConexoesRouteChildren,
  )

interface FabricaSocialRouteChildren {
  FabricaSocialBibliotecaRoute: typeof FabricaSocialBibliotecaRoute
  FabricaSocialConexoesRoute: typeof FabricaSocialConexoesRouteWithChildren
  FabricaSocialCriarPostagemRoute: typeof FabricaSocialCriarPostagemRoute
  FabricaSocialIndexRoute: typeof FabricaSocialIndexRoute
}

const FabricaSocialRouteChildren: FabricaSocialRouteChildren = {
  FabricaSocialBibliotecaRoute: FabricaSocialBibliotecaRoute,
  FabricaSocialConexoesRoute: FabricaSocialConexoesRouteWithChildren,
  FabricaSocialCriarPostagemRoute: FabricaSocialCriarPostagemRoute,
  FabricaSocialIndexRoute: FabricaSocialIndexRoute,
}

const FabricaSocialRouteWithChildren = FabricaSocialRoute._addFileChildren(
  FabricaSocialRouteChildren,
)

interface FounderAnalyticsUsuariasRouteChildren {
  FounderAnalyticsUsuariasIdRoute: typeof FounderAnalyticsUsuariasIdRoute
}

const FounderAnalyticsUsuariasRouteChildren: FounderAnalyticsUsuariasRouteChildren =
  {
    FounderAnalyticsUsuariasIdRoute: FounderAnalyticsUsuariasIdRoute,
  }

const FounderAnalyticsUsuariasRouteWithChildren =
  FounderAnalyticsUsuariasRoute._addFileChildren(
    FounderAnalyticsUsuariasRouteChildren,
  )

interface FounderRouteChildren {
  FounderAlertasRoute: typeof FounderAlertasRoute
  FounderNumerosRoute: typeof FounderNumerosRoute
  FounderSaudeRoute: typeof FounderSaudeRoute
  FounderIndexRoute: typeof FounderIndexRoute
  FounderAnalyticsComportamentoRoute: typeof FounderAnalyticsComportamentoRoute
  FounderAnalyticsFuncionalidadesRoute: typeof FounderAnalyticsFuncionalidadesRoute
  FounderAnalyticsJornadasRoute: typeof FounderAnalyticsJornadasRoute
  FounderAnalyticsRetencaoRoute: typeof FounderAnalyticsRetencaoRoute
  FounderAnalyticsSegmentosRoute: typeof FounderAnalyticsSegmentosRoute
  FounderAnalyticsSessoesRoute: typeof FounderAnalyticsSessoesRoute
  FounderAnalyticsUsuariasRoute: typeof FounderAnalyticsUsuariasRouteWithChildren
  FounderFeaturesExperimentosRoute: typeof FounderFeaturesExperimentosRoute
  FounderFeaturesFlagsRoute: typeof FounderFeaturesFlagsRoute
  FounderFeaturesReleasesRoute: typeof FounderFeaturesReleasesRoute
  FounderInfraApiRoute: typeof FounderInfraApiRoute
  FounderInfraBancoRoute: typeof FounderInfraBancoRoute
  FounderInfraIaRoute: typeof FounderInfraIaRoute
  FounderInfraStorageRoute: typeof FounderInfraStorageRoute
  FounderNegocioAssinaturasRoute: typeof FounderNegocioAssinaturasRoute
  FounderNegocioChurnRoute: typeof FounderNegocioChurnRoute
  FounderNegocioConversaoRoute: typeof FounderNegocioConversaoRoute
  FounderNegocioReceitaRoute: typeof FounderNegocioReceitaRoute
  FounderOperacaoErrosRoute: typeof FounderOperacaoErrosRoute
  FounderOperacaoIntegracoesRoute: typeof FounderOperacaoIntegracoesRoute
  FounderOperacaoJobsRoute: typeof FounderOperacaoJobsRoute
  FounderOperacaoLogsRoute: typeof FounderOperacaoLogsRoute
  FounderProdutoAtivacaoRoute: typeof FounderProdutoAtivacaoRoute
  FounderProdutoExperimentosRoute: typeof FounderProdutoExperimentosRoute
  FounderProdutoFeedbackRoute: typeof FounderProdutoFeedbackRoute
  FounderProdutoFunilRoute: typeof FounderProdutoFunilRoute
  FounderAnalyticsIndexRoute: typeof FounderAnalyticsIndexRoute
}

const FounderRouteChildren: FounderRouteChildren = {
  FounderAlertasRoute: FounderAlertasRoute,
  FounderNumerosRoute: FounderNumerosRoute,
  FounderSaudeRoute: FounderSaudeRoute,
  FounderIndexRoute: FounderIndexRoute,
  FounderAnalyticsComportamentoRoute: FounderAnalyticsComportamentoRoute,
  FounderAnalyticsFuncionalidadesRoute: FounderAnalyticsFuncionalidadesRoute,
  FounderAnalyticsJornadasRoute: FounderAnalyticsJornadasRoute,
  FounderAnalyticsRetencaoRoute: FounderAnalyticsRetencaoRoute,
  FounderAnalyticsSegmentosRoute: FounderAnalyticsSegmentosRoute,
  FounderAnalyticsSessoesRoute: FounderAnalyticsSessoesRoute,
  FounderAnalyticsUsuariasRoute: FounderAnalyticsUsuariasRouteWithChildren,
  FounderFeaturesExperimentosRoute: FounderFeaturesExperimentosRoute,
  FounderFeaturesFlagsRoute: FounderFeaturesFlagsRoute,
  FounderFeaturesReleasesRoute: FounderFeaturesReleasesRoute,
  FounderInfraApiRoute: FounderInfraApiRoute,
  FounderInfraBancoRoute: FounderInfraBancoRoute,
  FounderInfraIaRoute: FounderInfraIaRoute,
  FounderInfraStorageRoute: FounderInfraStorageRoute,
  FounderNegocioAssinaturasRoute: FounderNegocioAssinaturasRoute,
  FounderNegocioChurnRoute: FounderNegocioChurnRoute,
  FounderNegocioConversaoRoute: FounderNegocioConversaoRoute,
  FounderNegocioReceitaRoute: FounderNegocioReceitaRoute,
  FounderOperacaoErrosRoute: FounderOperacaoErrosRoute,
  FounderOperacaoIntegracoesRoute: FounderOperacaoIntegracoesRoute,
  FounderOperacaoJobsRoute: FounderOperacaoJobsRoute,
  FounderOperacaoLogsRoute: FounderOperacaoLogsRoute,
  FounderProdutoAtivacaoRoute: FounderProdutoAtivacaoRoute,
  FounderProdutoExperimentosRoute: FounderProdutoExperimentosRoute,
  FounderProdutoFeedbackRoute: FounderProdutoFeedbackRoute,
  FounderProdutoFunilRoute: FounderProdutoFunilRoute,
  FounderAnalyticsIndexRoute: FounderAnalyticsIndexRoute,
}

const FounderRouteWithChildren =
  FounderRoute._addFileChildren(FounderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditoriaRoute: AuditoriaRoute,
  CentralRoute: CentralRoute,
  ConteudoRoute: ConteudoRoute,
  CrmRoute: CrmRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  EstrategicoRoute: EstrategicoRoute,
  FabricaSocialRoute: FabricaSocialRouteWithChildren,
  FerramentasRoute: FerramentasRoute,
  FlagsRoute: FlagsRoute,
  FounderRoute: FounderRouteWithChildren,
  FunilRoute: FunilRoute,
  GovernancaRoute: GovernancaRoute,
  KanbanRoute: KanbanRoute,
  LogsRoute: LogsRoute,
  ManualDaMarcaRoute: ManualDaMarcaRoute,
  NegocioRoute: NegocioRoute,
  NumerosRoute: NumerosRoute,
  PainelRoute: PainelRoute,
  QualidadeRoute: QualidadeRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogIdRoute: BlogIdRoute,
  BlogNovoRoute: BlogNovoRoute,
  ChamadosIdRoute: ChamadosIdRoute,
  ConteudoPoliaSlugRoute: ConteudoPoliaSlugRoute,
  PesquisasSlugRoute: PesquisasSlugRoute,
  UsuariosIdRoute: UsuariosIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChamadosIndexRoute: ChamadosIndexRoute,
  ConteudoPoliaIndexRoute: ConteudoPoliaIndexRoute,
  PesquisasIndexRoute: PesquisasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
